# Lec_7_23 Shift operator

![lec_3_ex_1](../../images/AMMI_2022_ex/AIMS2022-Lecture7-Grids-23.png)

Let G be a group acting on a set X, and let g, h be elements of G and x be an element of X. We want to show that the group action is commutative, i.e., (gh)x = g(hx).

To prove this, we will use the shift operator. Let Sg denote the shift operator corresponding to the element g of G, i.e., Sg(x) = gx for any x in X. Then, we have:

(gh)x = Sgh(x) = (Sg o Sh)(x) [by definition of group action]
               = Sg(Sh(x)) [by associativity of group operation]
               = g(hx) [by definition of group action]

Therefore, we can see that (gh)x = g(hx), and the group action is commutative.

Let G be a group and let X be a set. Let g and h be elements of G and let x be an element of X. We want to show that the group action is commutative, i.e., that g(h(x)) = h(g(x)).

To prove this, we will use the shift operator. Let Sg denote the shift operator corresponding to the element g of G, i.e., Sg(x) = gx for any x in X. Similarly, let Sh denote the shift operator corresponding to the element h of G, i.e., Sh(x) = hx for any x in X. Then, we have:

g(h(x)) = Sg(Sh(x)) = (Sg o Sh)(x) [by definition of group action]
= Sh(Sg(x)) = h(g(x)) [by definition of group action]

Therefore, we can see that g(h(x)) = h(g(x)), and the group action is commutative.

In [1]:
import numpy as np

In [3]:
shift_op = np.array(
          [[0, 1, 0, 0, 0],
           [0, 0, 1, 0, 0],
           [0, 0, 0, 1, 0],
           [0, 0, 0, 0, 1],
           [1, 0, 0, 0, 0],
           ])

In [6]:
data = np.arange(25).reshape([5,5])

In [7]:
data

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [9]:
np.matmul(data, shift_op)

array([[ 4,  0,  1,  2,  3],
       [ 9,  5,  6,  7,  8],
       [14, 10, 11, 12, 13],
       [19, 15, 16, 17, 18],
       [24, 20, 21, 22, 23]])

In [10]:
np.matmul(shift_op, data)

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [ 0,  1,  2,  3,  4]])

In [13]:
np.matmul(data, np.matmul(shift_op, shift_op))

array([[ 3,  4,  0,  1,  2],
       [ 8,  9,  5,  6,  7],
       [13, 14, 10, 11, 12],
       [18, 19, 15, 16, 17],
       [23, 24, 20, 21, 22]])